name: Azure WindUp Rulesets PR builder

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - 'releases/**'

jobs:

  windup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WindUp upstream repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup
          ref: ${{ github.base_ref }}
      - name: Set up MS Build of OpenJDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-azure-windup-build-${{ github.sha }}
            restore-keys:
                ${{ runner.os }}-maven-azure-windup-build
      - name: Build WindUp
        run: mvn -B clean install -DskipTests

  windup-rules-test:
    runs-on: ubuntu-latest
    needs: [windup-build]
    strategy:
      fail-fast: false
      matrix:
        tests-pattern: [ 'rules-reviewed/azure' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up MS Build of OpenJDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-azure-windup-rulesets-build-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-maven-azure-windup-build-${{ github.sha }}
      - name: Build
        run: mvn -B clean install -DskipTests
      - name: Test
        run: mvn -B test -f rules/ -DrunTestsMatching=${{ matrix.tests-pattern }} -Dtest=WindupRulesTest

  windup-rules-links-test:
    runs-on: ubuntu-latest
    needs: [windup-build]
    strategy:
        fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up MS Build of OpenJDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-azure-windup-rulesets-build-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-maven-azure-windup-build-${{ github.sha }}
      - name: Build
        run: mvn -B clean install -DskipTests
      - name: Test
        run: mvn -B test -f rules/ -Dtest=WindupRulesLinksTest
