name: Azure WindUp Rulesets PR builder

on:
  pull_request:
    branches:
      - master
      - 'releases/**'

jobs:

  windup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WindUp upstream repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup
          ref: ${{ github.base_ref }}
      - name: Set up MS Build of OpenJDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-windup-build-${{ github.sha }}
            restore-keys:
                ${{ runner.os }}-maven-windup-build
      - name: Build WindUp
        run: mvn -B clean install -DskipTests

  WindupRulesTest:
    runs-on: ubuntu-latest
    needs: [windup-build]
    strategy:
      fail-fast: false
      matrix:
        jdk-distribution: [ microsoft ]
        tests-pattern: [ 'rules-reviewed/azure' ]
        java-version: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up MS Build of OpenJDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.jdk-distribution }}
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-azure-windup-rulesets-build-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-maven-azure-windup-build-${{ github.sha }}
      - name: Build
        run: mvn -B clean install -DskipTests
      - name: Test
        run: mvn -B test -f rules/ -DrunTestsMatching=${{ matrix.tests-pattern }} -Dtest=WindupRulesTest

  WindupRulesLinksTest:
    runs-on: ubuntu-latest
    needs: [windup-build]
    strategy:
        fail-fast: false
        matrix:
            jdk-distribution: [ microsoft ]
            java-version: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up MS Build of OpenJDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.jdk-distribution }}
          java-package: jdk
          cache: 'maven'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-azure-windup-rulesets-build-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-maven-azure-windup-build-${{ github.sha }}
      - name: Build
        run: mvn -B clean install -DskipTests
      - name: Test
        run: mvn -B test -f rules/ -Dtest=WindupRulesLinksTest


